const expect = require('expect.js');
const part1 = require('./part1');
const part2 = require('./part2');

describe('Day 06: Part 1', () => {
  it('Should count have many unique tiles the guard visits', () => {
    expect(part1(`....#.....
.........#
..........
..#.......
.......#..
..........
.#..^.....
........#.
#.........
......#...`)).to.equal(41);
  });
});
describe('Day 06: Part 2', () => {
  it('Should calculate in how many ways the guard can get stuck in a loop', () => {
    expect(part2(`....#.....
.........#
..........
..#.......
.......#..
..........
.#..^.....
........#.
#.........
......#...`)).to.equal(6);
  });
});
